name: Deploy application
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy web application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up SSH
        env:
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock
          SSH_HOST_KEY: ${{ secrets.SSH_HOST_KEY }}
          SSH_HOST_NAME: ${{ secrets.SSH_HOST_NAME }}
          SSH_USER_KEY: ${{ secrets.SSH_USER_KEY }}
          SSH_USER_KEY_FILENAME: gha_user_key
        run: |
          mkdir -p "${HOME}/.ssh"
          echo "${SSH_HOST_NAME} ${SSH_HOST_KEY}" >> "${HOME}/.ssh/known_hosts"
          echo "${SSH_USER_KEY}" > "${HOME}/.ssh/${SSH_USER_KEY_FILENAME}"
          chmod 600 "${HOME}/.ssh/${SSH_USER_KEY_FILENAME}"
          ssh-agent -a "${SSH_AUTH_SOCK}" > /dev/null	
          ssh-add "${HOME}/.ssh/${SSH_USER_KEY_FILENAME}"

      - name: Deploy web app via rsync
        env:
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock
          SSH_DEST_PATH: ${{ secrets.SSH_DEST_PATH }}
          SSH_HOST_NAME: ${{ secrets.SSH_HOST_NAME }}
          SSH_USER_NAME: ${{ secrets.SSH_USER_NAME }}
        run: |
          rsync \
            --delete-after \
            --exclude='.git*' \
            -zqpr \
            . \
            "${SSH_USER_NAME}@${SSH_HOST_NAME}:${SSH_DEST_PATH}"
